### ISSUE TITLE
TypeError: _reactKakaoMapsSdk.Loader is not a constructor

### ISSUE THREAD

**Issue by joonas-yoon** [JaeSeoKim/react-kakao-maps-sdk#46]
안녕하세요, CRA로 프로젝트를 생성하고 test를 하면 아래와 같이 `Loader is not a constructor` 라는 오류가 발생합니다.

문서상에 안내된대로 사용했고, 실제 동작에는 문제가 없는데 Jest 에서 문제가 발생하네요.

```
 ● renders default

    TypeError: _reactKakaoMapsSdk.Loader is not a constructor

       9 |
      10 |   useEffect(() => {
    > 11 |     const script: Loader = new Loader({
         |                            ^
      12 |       appkey: process.env.REACT_APP_KAKAO_MAP_API_KEY as string,
      13 |       libraries: ["services", "clusterer"],
      14 |       retries: 3,

      at src/components/KakaoMap/MapLoader.tsx:11:28
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:23150:26)
      at commitPassiveMountOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24931:11)
      at commitPassiveMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24891:9)
      at commitPassiveMountEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24878:7)
      at commitPassiveMountEffects (node_modules/react-dom/cjs/react-dom.development.js:24866:3)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:27039:3)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:26984:14)
      at node_modules/react-dom/cjs/react-dom.development.js:26769:9
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:63:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:159:26)
      at render (node_modules/@testing-library/react/dist/pure.js:246:10)
      at Object.<anonymous> (src/App.test.tsx:8:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        8.23s, estimated 9s
Ran all test suites.
```

테스트 코드는 아래가 전부입니다.

```javascript
test("renders default", () => {
  render(<App />)
})
```

**Comment by JaeSeoKim** [comment]
해당 부분은 설명만으로 확인 하기 힘듭니다. 군대에 있어서 직접 환경 구축이 제한되는 상황 입니다..
해당 문제가 발생하는 환경을 구현후 OnlineIDE 플랫폼 (CodeSandBox 등)을 이용하여 공유 부탁드립니다.,.

**Comment by joonas-yoon** [comment]
네 ㅎㅎ IDE 접속은 다행히 되시나보군요. 환경 구축해서 공유드릴 수는 있는데, API 키를 매번 설정하기가 어렵네요.
KEY 부분만 빈칸으로 만들어서 드려도 실행하시기에는 괜찮을까요?

**Comment by JaeSeoKim** [comment]
네네 가능합니다! 하지만 해당 문제는 라이브러리의 문제 보다는 jest 및 webpack 설정에서 문제가 있는 것으로 보여서 해결까지 도움을 드릴 수 없을 수 있습니다..

**Comment by JaeSeoKim** [comment]
@joonas-yoon 오랫동안 업데이트가 없는 이슈여서, Close 처리 합니다. 추가로 이야기를 나눌 부분이 있다면 언제든지 Open 해주세요.!
